# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='jobs/companies/logos')),
                ('requirements', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField()),
                ('industries', models.ManyToManyField(related_name='job_fields', to='jobs.Industry')),
            ],
        ),
    ]
